/*
 * Qself KSP processor.
 *
 * Scans for objects annotated with @QselfFeature and generates
 * `sumicya.qself.gen.QselfFeatures` — a plain list of object references, so
 * the runtime never reflects on feature metadata.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package sumicya.qself.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration

class QselfFeatureProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        QselfFeatureProcessor(environment.codeGenerator, environment.logger)
}

class QselfFeatureProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private val ANNOTATION = "sumicya.qself.annotation.QselfFeature"

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(ANNOTATION)
            .filterIsInstance<KSClassDeclaration>()
            .toList()
        if (symbols.isEmpty()) {
            return emptyList()
        }

        val seen = HashSet<String>()
        val qualified = ArrayList<String>(symbols.size)
        for (symbol in symbols) {
            val qname = symbol.qualifiedName?.asString()
            if (qname == null) {
                logger.error("feature without qualified name: ${symbol.simpleName.asString()}")
                continue
            }
            if (symbol.classKind != ClassKind.OBJECT) {
                logger.error("@QselfFeature must be on an object: $qname")
                continue
            }
            if (!seen.add(qname)) {
                logger.error("duplicate feature: $qname")
                continue
            }
            qualified.add(qname)
        }

        logger.info("QselfFeatureProcessor: ${qualified.size} features")

        val sb = StringBuilder()
        sb.append("package sumicya.qself.gen\n\n")
        sb.append("import sumicya.qself.feature.QselfFeature\n\n")
        sb.append("/**\n * Generated by QselfFeatureProcessor. Do not edit.\n */\n")
        sb.append("object QselfFeatures {\n\n")
        sb.append("    @JvmStatic\n")
        sb.append("    val features: List<QselfFeature> = listOf(\n")
        for (qname in qualified) {
            sb.append("        ").append(qname).append(",\n")
        }
        sb.append("    )\n}\n")

        val deps = Dependencies(
            true,
            *symbols.mapNotNull { it.containingFile }.toTypedArray(),
        )
        codeGenerator.createNewFile(deps, "sumicya.qself.gen", "QselfFeatures")
            .bufferedWriter()
            .use { it.write(sb.toString()) }
        return emptyList()
    }
}
